create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null,
  email text unique,
  role text not null default 'customer'
    check (role in ('customer', 'artisan', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  name text primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  price numeric(10, 2) not null check (price >= 0),
  category text not null references public.categories (name),
  image text not null default '',
  stock integer not null default 0 check (stock >= 0),
  maker text not null,
  artisan_id uuid references public.profiles (id) on delete set null,
  rating numeric(2, 1) not null default 0 check (rating between 0 and 5),
  review_count integer not null default 0 check (review_count >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.cart (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete restrict,
  total numeric(10, 2) not null default 0 check (total >= 0),
  status text not null default 'Processing'
    check (status in ('Processing', 'Shipped', 'Delivered', 'Cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete restrict,
  quantity integer not null check (quantity > 0),
  price numeric(10, 2) not null check (price >= 0)
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text not null default '',
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select role
  from public.profiles
  where id = (select auth.uid())
$$;

create or replace function public.create_customer_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, name, email, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(coalesce(new.email, 'Customer'), '@', 1)),
    new.email,
    'customer'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create or replace function public.is_order_artisan(target_order_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.order_items oi
    join public.products p on p.id = oi.product_id
    where oi.order_id = target_order_id
      and p.artisan_id = (select auth.uid())
  )
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.create_customer_profile();

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.cart enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.reviews enable row level security;

drop policy if exists "Users can read their profile" on public.profiles;
create policy "Users can read their profile"
  on public.profiles for select to authenticated
  using (id = (select auth.uid()) or public.current_user_role() = 'admin');

drop policy if exists "Admins can manage profiles" on public.profiles;
create policy "Admins can manage profiles"
  on public.profiles for all to authenticated
  using (public.current_user_role() = 'admin')
  with check (public.current_user_role() = 'admin');

drop policy if exists "Anyone can read categories" on public.categories;
create policy "Anyone can read categories"
  on public.categories for select to anon, authenticated
  using (true);

drop policy if exists "Admins can manage categories" on public.categories;
create policy "Admins can manage categories"
  on public.categories for all to authenticated
  using (public.current_user_role() = 'admin')
  with check (public.current_user_role() = 'admin');

drop policy if exists "Anyone can read active products" on public.products;
create policy "Anyone can read active products"
  on public.products for select to anon, authenticated
  using (
    is_active
    or artisan_id = (select auth.uid())
    or public.current_user_role() = 'admin'
  );

drop policy if exists "Artisans can add their products" on public.products;
create policy "Artisans can add their products"
  on public.products for insert to authenticated
  with check (
    artisan_id = (select auth.uid())
    and public.current_user_role() = 'artisan'
  );

drop policy if exists "Artisans can update their products" on public.products;
create policy "Artisans can update their products"
  on public.products for update to authenticated
  using (
    artisan_id = (select auth.uid())
    and public.current_user_role() = 'artisan'
  )
  with check (
    artisan_id = (select auth.uid())
    and public.current_user_role() = 'artisan'
  );

drop policy if exists "Artisans can delete their products" on public.products;
create policy "Artisans can delete their products"
  on public.products for delete to authenticated
  using (
    artisan_id = (select auth.uid())
    and public.current_user_role() = 'artisan'
  );

drop policy if exists "Admins can manage products" on public.products;
create policy "Admins can manage products"
  on public.products for all to authenticated
  using (public.current_user_role() = 'admin')
  with check (public.current_user_role() = 'admin');

drop policy if exists "Users can manage their cart" on public.cart;
create policy "Users can manage their cart"
  on public.cart for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists "Customers and artisans can read related orders" on public.orders;
create policy "Customers and artisans can read related orders"
  on public.orders for select to authenticated
  using (
    user_id = (select auth.uid())
    or public.current_user_role() = 'admin'
    or public.is_order_artisan(id)
  );

drop policy if exists "Customers can create their own orders" on public.orders;
create policy "Customers can create their own orders"
  on public.orders for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and status = 'Processing'
  );

drop policy if exists "Artisans and admins can update order status" on public.orders;
create policy "Artisans and admins can update order status"
  on public.orders for update to authenticated
  using (
    public.current_user_role() = 'admin'
    or public.is_order_artisan(id)
  )
  with check (
    public.current_user_role() = 'admin'
    or public.is_order_artisan(id)
  );

drop policy if exists "Customers and artisans can read order items" on public.order_items;
create policy "Customers and artisans can read order items"
  on public.order_items for select to authenticated
  using (
    exists (
      select 1 from public.orders o
      where o.id = order_items.order_id
        and (
          o.user_id = (select auth.uid())
          or public.current_user_role() = 'admin'
        )
    )
    or exists (
      select 1 from public.products p
      where p.id = order_items.product_id
        and p.artisan_id = (select auth.uid())
    )
  );

drop policy if exists "Customers can add items to their orders" on public.order_items;
create policy "Customers can add items to their orders"
  on public.order_items for insert to authenticated
  with check (
    exists (
      select 1 from public.orders o
      where o.id = order_items.order_id
        and o.user_id = (select auth.uid())
        and o.status = 'Processing'
    )
  );

drop policy if exists "Anyone can read reviews" on public.reviews;
create policy "Anyone can read reviews"
  on public.reviews for select to anon, authenticated
  using (true);

drop policy if exists "Customers can review delivered purchases" on public.reviews;
create policy "Customers can review delivered purchases"
  on public.reviews for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and exists (
      select 1
      from public.orders o
      join public.order_items oi on oi.order_id = o.id
      where o.user_id = (select auth.uid())
        and o.status = 'Delivered'
        and oi.product_id = reviews.product_id
    )
  );

drop policy if exists "Customers can update their reviews" on public.reviews;
create policy "Customers can update their reviews"
  on public.reviews for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists "Customers can delete their reviews" on public.reviews;
create policy "Customers can delete their reviews"
  on public.reviews for delete to authenticated
  using (user_id = (select auth.uid()));

grant usage on schema public to anon, authenticated;
grant select on public.categories, public.products, public.reviews to anon, authenticated;
grant select, insert, update, delete on public.profiles, public.categories, public.products,
  public.cart, public.orders, public.order_items, public.reviews to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into public.categories (name)
values ('Pottery'), ('Jewelry'), ('Textiles'), ('Woodcraft')
on conflict (name) do nothing;

insert into public.products
  (id, name, description, price, category, image, stock, maker, rating, review_count)
values
  (1, 'The Sunday Vase', 'A softly sculpted ceramic vase, shaped and glazed by hand. Lovely with a few fresh stems, or just as it is.', 899, 'Pottery', 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=900&q=85', 10, 'Ananya Crafts', 4.9, 28),
  (2, 'Wildflower Hoops', 'Lightweight brass hoops with a one-of-a-kind organic finish. Hand-polished in Mira''s little Jaipur studio.', 649, 'Jewelry', 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=900&q=85', 15, 'Mira Studio', 4.8, 19),
  (3, 'Soft Earth Throw', 'Woven slowly on a traditional loom from soft, natural cotton. An easy layer for a favourite chair or a quiet evening.', 1499, 'Textiles', 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85', 8, 'Sundar Weaves', 5.0, 12),
  (4, 'Little Clay Bowl', 'A small, useful bowl with a warm, earthy glaze. Each one is thrown and finished by hand, so no two are quite alike.', 599, 'Pottery', 'https://images.unsplash.com/photo-1493106641515-6b5631de4bb9?auto=format&fit=crop&w=900&q=85', 15, 'Ananya Crafts', 4.9, 16),
  (5, 'Carved Keepsake Box', 'A little keepsake box carved from responsibly sourced wood. Made to keep tiny treasures in one safe place.', 1199, 'Woodcraft', 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=85', 5, 'Neem & Grain', 4.7, 9),
  (6, 'Sunbeam Pendant', 'A simple brass pendant with a gently hammered surface that catches the light. Finished by hand and made to wear every day.', 799, 'Jewelry', 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=900&q=85', 12, 'Mira Studio', 4.8, 21),
  (7, 'Terracotta Planter', 'A warm terracotta planter with a simple, timeless shape. Each piece is formed and finished by hand.', 749, 'Pottery', 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=900&q=85', 10, 'Earth & Ember', 4.8, 14),
  (8, 'Golden Hour Earrings', 'Sculptural gold-tone earrings with a soft, organic shape. A little statement piece, made in small batches.', 899, 'Jewelry', 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=900&q=85', 9, 'Mira Studio', 4.9, 11),
  (9, 'Indigo Table Runner', 'A handwoven table runner in a rich indigo-inspired palette, made to bring a little warmth to everyday meals.', 1099, 'Textiles', 'https://images.unsplash.com/photo-1600166898405-da9535204843?auto=format&fit=crop&w=900&q=85', 7, 'Sundar Weaves', 4.8, 17),
  (10, 'Carved Serving Board', 'A sturdy serving board shaped from natural wood, with a smooth hand-finished surface and its own unique grain.', 1399, 'Woodcraft', 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=900&q=85', 6, 'Neem & Grain', 5.0, 8),
  (11, 'Speckled Clay Mug', 'A comfortable, hand-shaped ceramic mug with a warm speckled glaze. Each one has its own little character.', 549, 'Pottery', 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=85', 18, 'Ananya Crafts', 4.9, 23),
  (12, 'Meadow Blockprint Scarf', 'A soft, lightweight scarf with a cheerful hand-printed pattern. Made in small batches by skilled textile makers.', 1299, 'Textiles', 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=900&q=85', 9, 'Sundar Weaves', 4.8, 10)
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.products', 'id'),
  coalesce((select max(id) from public.products), 1)
);
